requires 'Encode',                                   0;
requires 'FindBin',                                  0;
requires 'JSON::XS',                                 '2.33';
requires 'AnyEvent',                                 '7.04';
requires 'AnyEvent::HTTP::Request',                  '0.301';
requires 'Plack::Request',                           '1.0020';
requires 'Twiggy',                                   '0.1021';
requires 'Text::VisualWidth',                        '0.02';
requires 'git://github.com/moznion/Yancha--Bot.git', '0.10';
